Feature/user authorization
mlshvch/news-portal pull request #5
Opened 2021-12-22 18:08 UTC by mlshvch

# Description

Add user authorization. Roles can be assigned to authenticated users.

- Reader: can read news
- Correspondent: can read and create news, update and delete only the news he has created
- Editor: can approve, create, edit and delete all the news 
- Admin: resource administrator

## Trello card link

https://trello.com/c/S4XdP7BE/11-authorization-roles

# Checklist:

- [x] My code fixes the problem or adds required functionality
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove that my feature works
- [x] New and existing unit tests pass locally with my changes

# Additional requirements:

- [x] Does your code require any migrations to be ran?
- [x] Does your code require installing any new gems or system dependencies?
- [ ] Does your code require any changes to current deployment process?

# Additional Information

2021-12-24 20:38 UTC, mlshvch commented
Test are not ready yet.

2022-01-04 11:53 UTC, blackp0is0n requested changes

2022-01-04 11:53 UTC, blackp0is0n commented on app/controllers/news_articles_controller.rb
> +    @news_article = policy_scope(NewsArticle).new(news_article_params)
@news_article = NewsArticle.new(news_article_params)
authorize @news_article

2022-01-04 11:53 UTC, blackp0is0n commented on app/controllers/news_articles_controller.rb
> +        authorize @news_article
authorise should be before update

2022-01-04 11:53 UTC, blackp0is0n commented on app/controllers/news_articles_controller.rb
> +    policy_scope(NewsArticle).find(params[:id]).destroy
`authorize @news_article`
`@news_article.destroy`

2022-01-04 11:53 UTC, blackp0is0n commented on app/controllers/news_articles_controller.rb
> +  before_action :authenticate_user!, except: :index
Pls remove this Line and move following:
  ```
  after_action :verify_authorized, except: :index, unless: :devise_controller?
  after_action :verify_policy_scoped, only: :index
  ```
  to application controller

2022-01-04 14:18 UTC, blackp0is0n approved these changes

2022-01-04 14:25 UTC, merged